spring:
  application:
    name: jonalabels-backend

  main:
    lazy-initialization: true

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/etiquetas_rfq_db}
    username: ${SPRING_DATASOURCE_USERNAME:JonaDev1230}
    password: ${SPRING_DATASOURCE_PASSWORD:password_seguro_123}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
      minimum-idle: 1

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    clean-on-validation-error: true
    clean-disabled: false

  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: ${JWT_SECRET:dGhpcy1pcy1hLXZlcnktbG9uZy1zZWNyZXQta2V5LWZvci1oZWFkZXItYmFzZWQtZW5jb2RpbmctaW4tYmFzZTY0LWZvci1qd3Qtc2lnbmluZw==}
  access-expiration: ${JWT_ACCESS_EXPIRATION:900000}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION:604800000}
  cookie-secure: ${JWT_COOKIE_SECURE:false}
  cookie-same-site: ${JWT_COOKIE_SAME_SITE:Lax}

app:
  admin:
    email: ${ADMIN_EMAIL:admin@jonalabels.com}


CLOUDINARY_URL: "cloudinary://tu_api_key:tu_api_secret@tu_cloud_name"